Repository FLearningg/FLearning_App, pull requests merged in 2025-06, with the labels that each got.

#3 [FLNAPP-4][UI][Feat] Add Launching, SignIn, SignUp, FillProfile.
  .gitignore
  App.tsx
  assets/images/AppleIcon.png
  assets/images/GoogleIcon.png
  assets/images/LOGO.png
  assets/images/LogoContentBlue.png
  assets/images/SHAPE.png
  assets/images/UserDefaultImage.png
  package-lock.json
  package.json
  src/components/ButtonNavigate.tsx
  src/components/Launching.tsx
  src/components/authentication/FillProfile.tsx
  src/components/authentication/FillProfileHeader.tsx
  src/components/authentication/LoginPage.tsx
  src/components/authentication/SignUp.tsx
  src/components/authentication/StartPage.tsx
  src/navigation/MainRoute.tsx
  src/navigation/a.tsx
  src/types/NavigationType.ts
Labels: Authentication

#5 [FLNAPP-5][UI] Add Forgot Password Screens UI
  App.tsx
  app.json
  assets/font/OPTIFrankfurter-Medium.otf
  package-lock.json
  package.json
  src/components/authentication/LoginPage.tsx
  src/navigation/MainRoute.tsx
  src/screens/ForgotPasswordScreen/CongratulationsScreen.tsx
  src/screens/ForgotPasswordScreen/CreateNewPasswordScreen.tsx
  src/screens/ForgotPasswordScreen/ForgotPasswordScreen.tsx
  src/screens/ForgotPasswordScreen/VerificationCodeScreen.tsx
  src/types/NavigationType.ts
Labels: Authentication

#6 [FLNAPP-12][UI] Update Route + Transition For HomeScreen
  src/components/authentication/LoginPage.tsx
  src/navigation/HomeRoutes.tsx
  src/navigation/MainRoute.tsx
  src/screens/CategoryScreen/CategoryScreen.tsx
  src/screens/ForgotPasswordScreen/ForgotPasswordScreen.tsx
  src/screens/HomeScreen/HomeScreen.tsx
  src/screens/SearchScreen/SearchScreen.tsx
  src/types/NavigationType.ts
Labels: enhancement

#7 [FLNAPP-12][UI] Update Route + Delete Font
  App.tsx
  assets/font/OPTIFrankfurter-Medium.otf
  src/navigation/MainRoute.tsx
  src/screens/ForgotPasswordScreen/CongratulationsScreen.tsx
  src/screens/ForgotPasswordScreen/CreateNewPasswordScreen.tsx
  src/screens/ForgotPasswordScreen/ForgotPasswordScreen.tsx
  src/screens/ForgotPasswordScreen/VerificationCodeScreen.tsx
  src/screens/HomeScreen/HomeScreen.tsx
  src/screens/courses/OnlineCourses.tsx
  src/screens/courses/PopularCourses.tsx
  src/types/NavigationType.ts
Labels: enhancement

#10 [Bug][Fix][UI] Fix Forgot password UI
  assets/font/OPTIFrankfurter-Medium.otf
  src/screens/ForgotPasswordScreen/CongratulationsScreen.tsx
  src/screens/ForgotPasswordScreen/CreateNewPasswordScreen.tsx
  src/screens/ForgotPasswordScreen/ForgotPasswordScreen.tsx
  src/screens/ForgotPasswordScreen/VerificationCodeScreen.tsx
Labels: bug

#9 [FLNAPP-16][UI] Prevent users from returning to the previous screen while in HomeScreen
  src/screens/HomeScreen/HomeScreen.tsx
Labels: enhancement
